### ISSUE TITLE
Add website URL in GitHub repo

### ISSUE THREAD

**Issue by DenisCarriere** [grigio/eosfilestore-web#2]
Would be nice to have the website URL listed in the GitHub repo at the top (even if it's a test url).

https://eosfilestore.now.sh/

![image](https://user-images.githubusercontent.com/550895/43608137-6482f624-966e-11e8-87ce-d6d721a3bd03.png)

**Comment by grigio** [comment]
Surem it will come with the Scatter integration :)

**Comment by grigio** [comment]
added
